name: example-component-test
'on':
  push:
    branches:
      - master
  pull_request: null
  workflow_dispatch: null
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: ./
        with:
          working-directory: examples/component-tests
          component: true
