name: Hello World
'on': push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: 'echo Hello, world!'
      - name: Hello from Docker
        run: docker run hello-world
